In [1]:
import numpy as np

# Створення масиву з першими 10-ма натуральними числами
array = np.arange(1, 11)

# Виведення масиву
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
import numpy as np

# Створення двовимірного масиву розміром 3x3 заповнених нулями
matrix = np.zeros((3, 3))

# Виведення матриці
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np

# Створення двовимірного масиву розміром 5x5 заповнених випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(5, 5))

# Виведення матриці
print(matrix)

[[ 4  2  3  6  4]
 [ 2  4  8  3  2]
 [ 3  1  2  3  9]
 [ 2  5  3 10  1]
 [ 5  4  8  1  7]]


In [4]:
import numpy as np

# Створення двовимірного масиву розміром 4x4 заповнених випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(4, 4))

# Виведення матриці
print(matrix)

[[0.67984599 0.8772461  0.95088855 0.5535189 ]
 [0.15036939 0.77309138 0.1466846  0.28669703]
 [0.78205121 0.9730787  0.16432    0.25160959]
 [0.87039344 0.89666274 0.68869422 0.35259782]]


In [5]:
import numpy as np

# Створення двох одновимірних масивів розміром 5, заповнених випадковими цілими числами від 1 до 10
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)

# Виведення масивів
print("Array 1:", array1)
print("Array 2:", array2)

# Поелементні операції додавання, віднімання та множення
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

# Виведення результатів операцій
print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)

Array 1: [5 4 7 5 8]
Array 2: [2 2 2 8 9]
Addition: [ 7  6  9 13 17]
Subtraction: [ 3  2  5 -3 -1]
Multiplication: [10  8 14 40 72]


In [6]:
import numpy as np

# Створення двох векторів розміром 7, заповнення їх довільними числами
vector1 = np.array([1, 2, 3, 4, 5, 6, 7])
vector2 = np.array([7, 6, 5, 4, 3, 2, 1])

# Виведення векторів
print("Vector 1:", vector1)
print("Vector 2:", vector2)

# Знаходження скалярного добутку векторів
dot_product = np.dot(vector1, vector2)

# Виведення результату
print("Dot product:", dot_product)

Vector 1: [1 2 3 4 5 6 7]
Vector 2: [7 6 5 4 3 2 1]
Dot product: 84


In [7]:
import numpy as np

# Створення двох матриць розміром 2x2 та 2x3, заповнення їх випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

# Виведення матриць
print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

# Перемноження матриць
result = np.dot(matrix1, matrix2)

# Виведення результату
print("Result of multiplication:")
print(result)

Matrix 1:
[[ 1 10]
 [ 3  1]]
Matrix 2:
[[ 1  3  5]
 [10 10  1]]
Result of multiplication:
[[101 103  15]
 [ 13  19  16]]


In [8]:
import numpy as np

# Створення матриці розміром 3x3, заповнення її випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 3))

# Виведення матриці
print("Original matrix:")
print(matrix)

# Знаходження оберненої матриці
inverse_matrix = np.linalg.inv(matrix)

# Виведення оберненої матриці
print("Inverse matrix:")
print(inverse_matrix)

Original matrix:
[[10  2  1]
 [ 8  4 10]
 [ 5  6  6]]
Inverse matrix:
[[ 0.1097561   0.01829268 -0.04878049]
 [-0.00609756 -0.16768293  0.2804878 ]
 [-0.08536585  0.15243902 -0.07317073]]


In [9]:
import numpy as np

# Створення матриці розміром 4x4, заповнення її випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(4, 4))

# Виведення матриці
print("Original matrix:")
print(matrix)

# Транспонування матриці
transposed_matrix = matrix.T

# Виведення транспонованої матриці
print("Transposed matrix:")
print(transposed_matrix)

Original matrix:
[[0.93715257 0.87958791 0.59476257 0.55247486]
 [0.98591342 0.92139936 0.4266196  0.8433277 ]
 [0.41556864 0.31542761 0.42075717 0.30479338]
 [0.35240951 0.80648685 0.65701615 0.03216567]]
Transposed matrix:
[[0.93715257 0.98591342 0.41556864 0.35240951]
 [0.87958791 0.92139936 0.31542761 0.80648685]
 [0.59476257 0.4266196  0.42075717 0.65701615]
 [0.55247486 0.8433277  0.30479338 0.03216567]]


In [10]:
import numpy as np

# Створення матриці розміром 3x4, заповнення її випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створення вектора розміром 4, заповнення його випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=4)

# Виведення матриці та вектора
print("Matrix:")
print(matrix)
print("Vector:")
print(vector)

# Перемноження матриці на вектор
result = np.dot(matrix, vector)

# Виведення результату
print("Result of multiplication:")
print(result)

Matrix:
[[ 4  3 10  2]
 [ 4  4 10  5]
 [ 2  9  2  7]]
Vector:
[7 1 1 7]
Result of multiplication:
[55 77 74]


In [11]:
import numpy as np

# Створення матриці розміром 2x3, заповнення її випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(2, 3))

# Створення вектора розміром 3, заповнення його випадковими дійсними числами від 0 до 1
vector = np.random.uniform(0, 1, size=3)

# Виведення матриці та вектора
print("Matrix:")
print(matrix)
print("Vector:")
print(vector)

# Перемноження матриці на вектор
result = np.dot(matrix, vector)

# Виведення результату
print("Result of multiplication:")
print(result)

Matrix:
[[0.80211936 0.39226358 0.23754326]
 [0.48605105 0.35043509 0.06093691]]
Vector:
[0.99687031 0.48058475 0.51583641]
Result of multiplication:
[1.11065834 0.6843771 ]


In [12]:
import numpy as np

# Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Виведення матриць
print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

# Поелементне множення матриць
elementwise_product = np.multiply(matrix1, matrix2)

# Виведення результату
print("Elementwise product:")
print(elementwise_product)

Matrix 1:
[[ 3 10]
 [ 3  3]]
Matrix 2:
[[ 5 10]
 [ 6  6]]
Elementwise product:
[[ 15 100]
 [ 18  18]]


In [13]:
import numpy as np

# Створення двох матриць розміром 2x2, заповнення їх випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 2))

# Виведення матриць
print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

# Знаходження добутку матриць
product = np.matmul(matrix1, matrix2)

# Виведення результату
print("Product of matrices:")
print(product)

Matrix 1:
[[ 3 10]
 [ 4  7]]
Matrix 2:
[[10 10]
 [ 2  8]]
Product of matrices:
[[ 50 110]
 [ 54  96]]


In [14]:
import numpy as np

# Створення матриці розміром 5x5, заповнення її випадковими цілими числами від 1 до 100
matrix = np.random.randint(1, 101, size=(5, 5))

# Виведення матриці
print("Matrix:")
print(matrix)

# Знаходження суми елементів матриці
sum_of_elements = np.sum(matrix)

# Виведення результату
print("Sum of elements:", sum_of_elements)

Matrix:
[[60 16 23 17  8]
 [68 32  7 91 50]
 [79 50 78 77 14]
 [21 26 53 90 77]
 [97 81 86  8 69]]
Sum of elements: 1278


In [15]:
import numpy as np

# Створення двох матриць розміром 4x4, заповнення їх випадковими цілими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

# Виведення матриць
print("Matrix 1:")
print(matrix1)
print("Matrix 2:")
print(matrix2)

# Знаходження різниці матриць
difference = np.subtract(matrix1, matrix2)

# Виведення результату
print("Difference of matrices:")
print(difference)

Matrix 1:
[[ 7  2  4 10]
 [ 9  7  1  6]
 [ 2  6  2  5]
 [ 2  1  7 10]]
Matrix 2:
[[ 4  9  3  8]
 [ 1  7  3  4]
 [ 4  4 10  6]
 [ 5 10  6  6]]
Difference of matrices:
[[ 3 -7  1  2]
 [ 8  0 -2  2]
 [-2  2 -8 -1]
 [-3 -9  1  4]]


In [16]:
import numpy as np

# Створення матриці розміром 3x3, заповнення її випадковими дійсними числами від 0 до 1
matrix = np.random.uniform(0, 1, size=(3, 3))

# Виведення матриці
print("Matrix:")
print(matrix)

# Знаходження суми елементів кожного рядка матриці
row_sums = np.sum(matrix, axis=1)

# Виведення результату
print("Row sums:", row_sums)

Matrix:
[[0.57733893 0.28059138 0.94293308]
 [0.74990853 0.28773443 0.23530904]
 [0.747084   0.4273902  0.2013863 ]]
Row sums: [1.80086339 1.272952   1.37586049]


In [17]:
import numpy as np

# Створення матриці розміром 3x4 з довільними цілими числами
matrix = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Створення матриці з квадратами цих чисел
squared_matrix = np.square(matrix)

# Виведення матриць
print("Original matrix:")
print(matrix)
print("Squared matrix:")
print(squared_matrix)

Original matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Squared matrix:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [18]:
import numpy as np

# Створення вектора розміром 4 з довільними цілими числами від 1 до 50
vector = np.random.randint(1, 51, size=4)

# Знаходження вектора з квадратними коренями цих чисел
square_roots = np.sqrt(vector)

# Виведення векторів
print("Original vector:", vector)
print("Square roots:", square_roots)

Original vector: [25  4 46 25]
Square roots: [5.         2.         6.78232998 5.        ]
